### ISSUE TITLE
[BUG]: forced view is not working

### ISSUE THREAD

**Issue by Falcion** [Falcion/UNITADE.md#54]
### What the essence of the bug

Forced view and opening PDFs like markdown and etc. are not working, `ltReady` of `main.ts` throwns:
```console
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'app')
    at ltReady (VM227 plugin:unitade:976:10)
    at e.tryTrigger (app.js:1:726617)
    at e.trigger (app.js:1:726550)
    at t.trigger (app.js:1:2235641)
    at t.activeLeafEvents (app.js:1:2221334)
    at l (app.js:1:260204)
    at c (app.js:1:260320)
```

### Version of an project's essence

2.1.3

### On what OS you have encountered the bug.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Fixed in dev-preview of plugin's build, waiting for the release.
